---
- name: show start time
  shell: date +%T

- name: create vm dir
  file: path={{ vmDir }} state=directory
  tags: aa

- name: create vm image
  shell: qemu-img create -f qcow2 -b {{baseImageDir}}/{{baseImageName}}  {{vmDir}}/{{vmName}}.qcow2 creates={{vmDir}}/{{vmName}}.qcow2

- name: create xml file
  template: src=vm.xml.j2 dest={{vmDir}}/{{vmName}}.xml

- name: define vm
  virt: name={{vmName}} command=define xml={{ lookup('template', 'vm.xml.j2') }}

- name: create ifcfg-eth0 and hostname and hosts
  template: src="{{item.source}}" dest="{{item.destination}}"
  with_items: "{{create_files}}"

- name: copy ifcfg-eth0 and hostname and hosts
  shell: virt-copy-in -a {{vmDir}}/{{vmName}}.qcow2 {{vmDir}}/{{item.source}}  {{item.destination}}
  with_items: "{{copy_files}}"
  args:
    creates: "{{vmDir}}/networkbackup"

- file: path={{vmDir}}/networkbackup state=touch

- name: start vm
  virt:
      name: "{{vmName}}"
      state: running

- name: show end time
  shell: date +%T

